# Dependencies
markdown: kramdown
highlighter: rouge   # non e' un colore e' un sistema per sottolineare che funge con varie lingue

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
#color : '#057bfa'   # non chiaro come funga, c'e' un sito che spiega i colori  https://www.colorhexa.com/index.php (Sembra fungere solo con il nome del SITO = 4phycs)
exclude:            # questo mi pare escluda le dir varie dalla costruzione del sito
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: true  # PA l'originale era false

# Site meta
title: 4Phycs
#title-separator: "-"
tagline: 'Numbers and the world'
description: 'A simple Jekyll theme with a photo sidebar.'
keywords: 'connor, bär, designer, traveller, code, jekyll, developer, theme'
url: https://4phycs.github.io
baseurl: /summer
assets: /assets
images: /images/
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png

author:
  name: Paolo Avogadro
  bio: Hi, I'm Paolo, the author of this blog. Nice to meet you!
  image: author
  url: https://connorbaer.co
  email: paolo.avogadro@gmail.com
  twitter: 

social:
  twitter: 
  instagram: 
  github: https://github.com/4phycs

version: 2.0.0

github:
  repo: https://github.com/4phycs

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: https://github.com/4phycs
  Download: https://github.com/connor-baer/summer/archive/gh-pages.zip

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: en
      permalink: /:title/
