# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
headroom:             true
color:                '#115bb0'
exclude:              [CNAME, README.md, NOTES.md, LICENSE.md, .gitignore, package.json, bower.json, _js, _scss, _images, gulpfile.js, gulpconfig.js, node_modules, bower_components, gemfile, Gemfile.lock]
permalink:            /:title/
compress_html:
  clippings: all
  comments: all


# Site meta
title:                Skye
tagline:              'Form follows function'
description:          'A simple Jekyll theme with a photo sidebar.'
keywords:             'connor, bär, designer, traveller, code, jekyll, developer, theme'
url:                  http://skye.connorbaer.io
baseurl:              ''
assets:               /assets
images:               /images/
image:               main.jpg
logo:                 /assets/icons/apple-icon-144x144.png

author:
  name:               Connor Bär
  bio:                Hi, I'm Connor, the author of this blog. Nice to meet you!
  image:              author
  url:                http://connorbaer.io
  email:              hello@connorbaer.io
  twitter:            connor_baer

social:
  twitter:            https://twitter.com/connor_baer
  instagram:          https://instagram.com/connor_baer
  github:             https://github.com/connor-baer/skye
  medium:             https://blog.connorbaer.io

version:              1.0.0

github:
  repo:               https://github.com/connor-baer/skye


# Integrations
typekit:              fcv7rfe

# google_fonts:
#   name:             weights

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

facebook:
  app_id:             169140053203395
